---
abstract: unknown
author:
  - 'Vipul Ved Prakash <mail@vipul.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-Random
no_index:
  directory:
    - t
    - inc
requires:
  Class::Loader: '2.00'
  Math::Pari: '2.001804'
  Statistics::ChiSquare: '1.0000'
version: 1.54
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
